name: user_end 
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  crypto: ^3.0.6
  http: ^1.4.0
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  rive: ^0.13.20
  google_fonts: ^6.2.1
  hive: ^2.2.3
  firebase_messaging: 15.2.6
  flutter_local_notifications: ^17.2.3
  animate_do: ^4.2.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  get: ^4.7.2
  intl: ^0.20.2
  uuid: ^3.0.7
  generative_ai_dart: ^0.1.2
  google_generative_language_api: ^0.2.1
  google_generative_ai:
  font_awesome_flutter:
  pdf:
  syncfusion_flutter_pdf:
  file_picker:
  flutter_quill: ^11.4.1
  flutter_quill_extensions: ^11.0.0
  video_player: ^2.8.2
  shimmer: ^3.0.0
  rename: ^3.1.0
  url_launcher: ^6.2.4
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo_image.png

flutter:
  uses-material-design: true

  assets:
    - assets/animations/loading_animation.json
    - assets/animations/like_animation.json
    - assets/animations/empty_state_animation.json
    - assets/animations/quiz_animation.json
    - assets/animations/connection_animation.json
    - assets/animations/error_animation.json
    - assets/animations/particle_animation.json
    - assets/animations/time_up.json
    - assets/animations/warning.json
    - assets/animations/empty_trophy.json
    - assets/animations/gold_medal.json
    - assets/animations/silver_medal.json
    - assets/animations/loading_trophy.json
    - assets/video/Logo_Animation.mp4
    - assets/video/Logo_Animation_4.mp4
    - assets/images/logo_vibrant_minds.jpg
    - assets/images/logo_vibrant_minds.png
    - assets/images/logo_image.png
    - assets/images/vmt.png

# flutter_native_splash:
#   color: "#FFFFFF"
#   image: assets/images/vmt.png
#   fullscreen: true
#   android: true
#   ios: true
#   android_gravity: center
#   ios_content_mode: scaleAspectFit
