name: user_end
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  crypto: ^3.0.6
  http: ^1.4.0
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  rive: ^0.13.20
  google_fonts: ^6.2.1
  get: ^4.7.2
  intl: ^0.19.0
  uuid: ^3.0.7
  generative_ai_dart: ^0.1.2
  google_generative_language_api: ^0.2.1
  google_generative_ai:
  font_awesome_flutter:
#  riverpod: ^2.0.0
#  flutter_3d_object: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/loading_animation.json
    - assets/animations/like_animation.json
    - assets/animations/empty_state_animation.json
    - assets/animations/quiz_animation.json
    - assets/animations/connection_animation.json
    - assets/animations/error_animation.json
    - assets/animations/particle_animation.json
    - assets/animations/time_up.json
    - assets/animations/warning.json
    - assets/animations/empty_trophy.json
    - assets/animations/gold_medal.json
    - assets/animations/silver_medal.json
    - assets/animations/loading_trophy.json
    - assets/animations/empty_trophy.json
