// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYrbPw8shBMNa1DtLVU64dkxyXMAh0Exc',
    appId: '1:907449237702:web:5ba656b13f362657ea17c7',
    messagingSenderId: '907449237702',
    projectId: 'vmt-firebase',
    authDomain: 'vmt-firebase.firebaseapp.com',
    databaseURL: 'https://vmt-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'vmt-firebase.firebasestorage.app',
    measurementId: 'G-6QWTR1BC5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB29bIr_lWxu_QmJJIb3MwCRc_h-W2AdyQ',
    appId: '1:907449237702:android:69f225ca88d1e32bea17c7',
    messagingSenderId: '907449237702',
    projectId: 'vmt-firebase',
    databaseURL: 'https://vmt-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'vmt-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiQ443wfUrglHFS_nxcQH-uKdY-1k5idw',
    appId: '1:907449237702:ios:b30a71e6b81952b3ea17c7',
    messagingSenderId: '907449237702',
    projectId: 'vmt-firebase',
    databaseURL: 'https://vmt-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'vmt-firebase.firebasestorage.app',
    iosBundleId: 'com.example.userEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiQ443wfUrglHFS_nxcQH-uKdY-1k5idw',
    appId: '1:907449237702:ios:b30a71e6b81952b3ea17c7',
    messagingSenderId: '907449237702',
    projectId: 'vmt-firebase',
    databaseURL: 'https://vmt-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'vmt-firebase.firebasestorage.app',
    iosBundleId: 'com.example.userEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYrbPw8shBMNa1DtLVU64dkxyXMAh0Exc',
    appId: '1:907449237702:web:1dcac714c27ca5e7ea17c7',
    messagingSenderId: '907449237702',
    projectId: 'vmt-firebase',
    authDomain: 'vmt-firebase.firebaseapp.com',
    databaseURL: 'https://vmt-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'vmt-firebase.firebasestorage.app',
    measurementId: 'G-ZL9CC582XE',
  );
}
