import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_authenticator/amplify_authenticator.dart';

import 'firebase_options.dart';
import 'amplifyconfiguration.dart';
import 'services/firestore_service.dart';
import 'widgets/profile_cards/profile_redirector.dart'; // Main app landing screen
import 'theme/vibrant_theme.dart'; // ✅ Your custom theme

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize Amplify
  await _configureAmplify();

  runApp(
    MultiProvider(
      providers: [
        Provider<FirestoreService>(
          create: (_) => FirestoreService(FirebaseFirestore.instance),
        ),
      ],
      child: const MyApp(),
    ),
  );
}

Future<void> _configureAmplify() async {
  try {
    await Amplify.addPlugin(AmplifyAuthCognito());
    await Amplify.configure(amplifyconfig);
  } catch (e) {
    safePrint('Amplify error: $e');
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Authenticator(
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Vibrant Minds App',
        theme: VibrantTheme.themeData, // ✅ Use your theme here
        builder: Authenticator.builder(), // Required for Amplify Authenticator
        home: const CombinedRedirector(),
      ),
    );
  }
}

/// This widget decides which screen to show initially.
/// You can adjust this logic based on user roles or states.
class CombinedRedirector extends StatelessWidget {
  const CombinedRedirector({super.key});

  @override
  Widget build(BuildContext context) {
    return const ProfileRedirector(); // Role-based redirect
  }
}
// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // This file is generated by flutterfire CLI

// import 'widgets/profile_cards/education_section.dart';

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   runApp(const EducationTestApp());
// }


// class EducationTestApp extends StatelessWidget {
//   const EducationTestApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Education Section Test',
//       home: Scaffold(
//         appBar: AppBar(title: const Text('Test Education Section')),
//         body: const Padding(
//           padding: EdgeInsets.all(16.0),
//           child: EducationTestScreen(),
//         ),
//       ),
//     );
//   }
// }

// class EducationTestScreen extends StatefulWidget {
//   const EducationTestScreen({super.key});

//   @override
//   State<EducationTestScreen> createState() => _EducationTestScreenState();
// }

// class _EducationTestScreenState extends State<EducationTestScreen> {
//   final GlobalKey<EducationSectionState> _educationKey = GlobalKey();

//   Map<String, dynamic> savedData = {};

//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Expanded(
//           child: EducationSection(
//             key: _educationKey,
//             onSaved: (data) {
//               setState(() {
//                 savedData = data;
//               });
//               debugPrint("Saved Data: $data");
//               ScaffoldMessenger.of(context).showSnackBar(
//                 const SnackBar(content: Text("Saved Successfully!")),
//               );
//             },
//           ),
//         ),
//         ElevatedButton(
//           onPressed: () {
//             _educationKey.currentState?.save();
//           },
//           child: const Text("Trigger Save"),
//         ),
//         if (savedData.isNotEmpty)
//           Padding(
//             padding: const EdgeInsets.all(8.0),
//             child: Text(
//               "Saved: ${savedData.toString()}",
//               style: const TextStyle(fontWeight: FontWeight.bold),
//             ),
//           ),
//       ],
//     );
//   }
// }
